version: '3'
services:
        nginx:
                image: nginx
                environment:
                        SERVER_NAME: localhost
                        NGINX_CLIENT_MAX_BODY_SIZE: 10M
                volumes:
                        - ./nginx/templates:/etc/nginx/templates
                        - ./nginx/html:/usr/share/nginx/html
                ports:
                        - '8080:80'

